# Generated by Django 4.0.3 on 2022-06-04 01:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Comida')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Entrada')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fondo')),
                ('description3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Postre')),
            ],
            options={
                'verbose_name': 'Banqueteria',
                'verbose_name_plural': 'Banqueteria',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('rut', models.CharField(max_length=100, verbose_name='Rut')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Bebestible')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
            ],
            options={
                'verbose_name': 'Bebestible',
                'verbose_name_plural': 'Bebestibles',
            },
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Entretenimiento')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
            ],
            options={
                'verbose_name': 'Entretenimiento',
                'verbose_name_plural': 'Entretenimiento',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Musica')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musica',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Recinto')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recinto',
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='ID de busqueda')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('booking_date', models.CharField(max_length=30, verbose_name='fecha de reserva')),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('description', models.TextField(max_length=250, verbose_name='Descripción')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('people', models.PositiveIntegerField(verbose_name='Invitados')),
                ('value', models.PositiveIntegerField(verbose_name='Total a pagar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima edición')),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bada_app.catering', verbose_name='Comida')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.customer', verbose_name='Cliente')),
                ('drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bada_app.drinks', verbose_name='Bebestible')),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bada_app.entertainment', verbose_name='Entretenimiento')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bada_app.music', verbose_name='Musica')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bada_app.site', verbose_name='Recinto')),
            ],
            options={
                'verbose_name': 'Evento reservado',
                'verbose_name_plural': 'Eventos reservados',
                'ordering': ['-created'],
            },
        ),
    ]
