# Generated by Django 4.0.3 on 2022-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Estado_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('recinto', models.CharField(max_length=50)),
                ('banqueteria', models.CharField(max_length=50)),
                ('animacion', models.CharField(max_length=50)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=50)),
                ('iluminacion', models.CharField(max_length=50)),
                ('fotografo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Consultar evento',
                'verbose_name_plural': 'Consultar evento',
            },
        ),
    ]
