# Generated by Django 4.0.3 on 2022-06-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='event_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evento_reservado', to='bada_app.eventbooking'),
        ),
    ]
