# Generated by Django 4.0.3 on 2022-05-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.CharField(default=77788272951193, editable=False, max_length=100, verbose_name='ID de busqueda'),
        ),
    ]
