# Generated by Django 4.0.3 on 2022-05-20 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.UUIDField(default=uuid.UUID('a36b72f9-3fde-42cb-82fd-ba617feca114'), editable=False, primary_key=True, serialize=False, verbose_name='ID de busqueda'),
        ),
    ]
