# Generated by Django 4.0.3 on 2022-06-04 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.catering', verbose_name='Comida'),
        ),
    ]
