# Generated by Django 4.0.3 on 2022-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
