# Generated by Django 4.0.3 on 2022-05-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='adress',
            new_name='address',
        ),
    ]
