# Generated by Django 4.0.3 on 2022-05-20 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de busqueda'),
        ),
    ]
