# Generated by Django 4.0.3 on 2022-05-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.UUIDField(default='bb2fb76c', editable=False, primary_key=True, serialize=False, verbose_name='ID de busqueda'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total a pagar'),
        ),
    ]
