# Generated by Django 4.0.3 on 2022-06-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Comida')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Entrada')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fondo')),
                ('description3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Postre')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Banqueteria',
                'verbose_name_plural': 'Banqueteria',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Bebestible')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Bebestible',
                'verbose_name_plural': 'Bebestibles',
            },
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Entretenimiento')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Entretenimiento',
                'verbose_name_plural': 'Entretenimiento',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Musica')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musica',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Recinto')),
                ('urlBase', models.URLField(max_length=500, verbose_name='URL de la imagen')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recinto',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='banquetry',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='group',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='description',
            field=models.TextField(default=None, max_length=250, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='urlBase',
            field=models.URLField(default=None, max_length=500, verbose_name='URL de la imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='booking_date',
            field=models.CharField(default=None, max_length=30, verbose_name='fecha de reserva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='capacity',
            field=models.PositiveIntegerField(default=None, verbose_name='Capacidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='event_type',
            field=models.CharField(default=None, max_length=50, verbose_name='Tipo de evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='value',
            field=models.PositiveIntegerField(default=None, verbose_name='Total a pagar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='catering',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.catering', verbose_name='Comida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='drinks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.drinks', verbose_name='Bebestible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='entertainment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.entertainment', verbose_name='Entretenimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bada_app.music', verbose_name='Musica'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.site', verbose_name='Recinto'),
            preserve_default=False,
        ),
    ]
