# Generated by Django 4.0.3 on 2022-04-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0002_alter_slider_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider de fotos'},
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider', verbose_name='Foto de perfil'),
        ),
    ]
