# Generated by Django 4.0.3 on 2022-06-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0002_catering_drinks_entertainment_music_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='capacity',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='people',
            field=models.PositiveIntegerField(default=None, verbose_name='Invitados'),
            preserve_default=False,
        ),
    ]
