# Generated by Django 4.0.3 on 2022-05-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0002_alter_eventbooking_search_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.CharField(default=222300426236157, editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='ID de busqueda'),
        ),
    ]
