# Generated by Django 4.0.3 on 2022-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0002_mailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
