# Generated by Django 4.0.3 on 2022-06-04 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0002_alter_eventbooking_catering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='drinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.drinks', verbose_name='Bebestible'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='entertainment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.entertainment', verbose_name='Entretenimiento'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.music', verbose_name='Musica'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.site', verbose_name='Recinto'),
        ),
    ]
