# Generated by Django 4.0.3 on 2022-04-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0003_alter_slider_options_slider_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contacto'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Consultar evento', 'verbose_name_plural': 'Consultar evento'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider de fotos', 'verbose_name_plural': 'Slider de fotos'},
        ),
    ]
