# Generated by Django 4.0.3 on 2022-06-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0003_remove_eventbooking_capacity_eventbooking_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catering',
            name='value',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='value',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='value',
        ),
        migrations.RemoveField(
            model_name='music',
            name='value',
        ),
        migrations.RemoveField(
            model_name='site',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='site',
            name='value',
        ),
    ]
