# Generated by Django 4.0.3 on 2022-05-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0003_alter_eventbooking_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.UUIDField(default='6a5853fe', editable=False, primary_key=True, serialize=False, verbose_name='ID de busqueda'),
        ),
    ]
