# Generated by Django 4.0.3 on 2022-06-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0003_alter_eventbooking_drinks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='customer',
        ),
    ]
