# Generated by Django 4.0.3 on 2022-06-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0004_remove_eventbooking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='catering',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='entertainment',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='music',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='site',
        ),
        migrations.AddField(
            model_name='catering',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinks',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainment',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Evento'),
            preserve_default=False,
        ),
    ]
