# Generated by Django 4.0.3 on 2022-05-20 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0004_alter_eventbooking_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.UUIDField(default=uuid.UUID('3d0beeec-01e5-4021-97a2-3be52dfb5ca6'), editable=False, primary_key=True, serialize=False, verbose_name='ID de busqueda'),
        ),
    ]
