# Generated by Django 4.0.3 on 2022-06-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0004_remove_catering_value_remove_drinks_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
