# Generated by Django 4.0.3 on 2022-05-17 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0005_alter_eventbooking_search_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbooking',
            options={'ordering': ['-created'], 'verbose_name': 'Evento reservado', 'verbose_name_plural': 'Eventos reservados'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.CharField(default=218472046251284, editable=False, max_length=100, verbose_name='ID de busqueda'),
        ),
    ]
