# Generated by Django 4.0.3 on 2022-06-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0005_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
