# Generated by Django 4.0.3 on 2022-06-04 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0005_remove_eventbooking_catering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catering',
            name='event',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='event',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='music',
            name='event',
        ),
        migrations.RemoveField(
            model_name='site',
            name='event',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='catering',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.catering', verbose_name='Comida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bada_app.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='drinks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.drinks', verbose_name='Bebestible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='entertainment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.entertainment', verbose_name='Entretenimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='music',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.music', verbose_name='Musica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.site', verbose_name='Recinto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de busqueda'),
        ),
    ]
