# Generated by Django 4.0.3 on 2022-05-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0006_alter_eventbooking_options_alter_customer_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.CharField(default=47221016897193, editable=False, max_length=100, verbose_name='ID de busqueda'),
        ),
    ]
