# Generated by Django 4.0.3 on 2022-06-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0006_remove_catering_event_remove_customer_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='event_booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bada_app.eventbooking', verbose_name='Eventos reservados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='catering',
            field=models.CharField(max_length=100, verbose_name='Catering'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='drinks',
            field=models.CharField(max_length=100, verbose_name='Bebidas'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='entertainment',
            field=models.CharField(max_length=100, verbose_name='Entretenimiento'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='music',
            field=models.CharField(max_length=100, verbose_name='Música'),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='site',
            field=models.CharField(max_length=100, verbose_name='Sitio'),
        ),
        migrations.DeleteModel(
            name='Catering',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='Entertainment',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
