# Generated by Django 4.0.3 on 2022-05-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0007_alter_eventbooking_search_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='photographer',
            new_name='entertainment',
        ),
        migrations.RenameField(
            model_name='eventbooking',
            old_name='animation',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='ilumination',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='adress',
            field=models.CharField(default=None, max_length=200, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='music',
            field=models.CharField(default=None, max_length=100, verbose_name='Musica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='search_id',
            field=models.CharField(default=139033139703942, editable=False, max_length=100, verbose_name='ID de busqueda'),
        ),
    ]
