# Generated by Django 4.0.3 on 2022-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bada_app', '0007_remove_eventbooking_customer_customer_event_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='catering',
            field=models.CharField(max_length=100, verbose_name='Banqueteria'),
        ),
    ]
