# Generated by Django 4.0.3 on 2022-05-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_urlbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='urlBase',
            field=models.CharField(default='https://badaeventos.herokuapp.com', editable=False, max_length=200, verbose_name='API'),
        ),
    ]
