# Generated by Django 4.0.3 on 2022-05-17 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banquetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Item')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Banqueteria',
                'verbose_name_plural': 'Banqueteria',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Musica')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musica',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100, verbose_name='Recinto')),
                ('adress', models.CharField(max_length=200, verbose_name='Dirección')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recinto',
            },
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Juegos')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Juegos',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='EventTipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('banquetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Banqueteria', to='default_event.banquetry')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music', to='default_event.music')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recinto', to='default_event.site')),
                ('toys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Juegos', to='default_event.toys')),
            ],
            options={
                'verbose_name': 'Evento predefinido',
                'verbose_name_plural': 'Eventos predefinidos',
            },
        ),
    ]
