# Generated by Django 4.0.3 on 2022-05-18 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banquetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Item')),
                ('image', models.ImageField(upload_to='banquetry/images', verbose_name='Imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Banqueteria',
                'verbose_name_plural': 'Banqueteria',
            },
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Entretenimiento')),
                ('image', models.ImageField(upload_to='entertainment/images', verbose_name='Imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Entretenimiento',
                'verbose_name_plural': 'Entretenimiento',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Tipo de publico')),
            ],
            options={
                'verbose_name': 'Tipo de publico',
                'verbose_name_plural': 'Tipo de publico',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Musica')),
                ('image', models.ImageField(upload_to='music/images', verbose_name='Imagen')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('description2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción2')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musica',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100, verbose_name='Recinto')),
                ('image', models.ImageField(upload_to='site/images', verbose_name='Imagen')),
                ('adress', models.CharField(max_length=200, verbose_name='Dirección')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recinto',
            },
        ),
        migrations.CreateModel(
            name='EventTipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('image', models.ImageField(upload_to='event_tipe/images', verbose_name='Imagen')),
                ('banquetry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default_event.banquetry', verbose_name='Banqueteria')),
                ('entertainment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default_event.entertainment', verbose_name='Entretenimiento')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default_event.group', verbose_name='Tipo de publico')),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default_event.music', verbose_name='Musica')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_event.site', verbose_name='Recinto')),
            ],
            options={
                'verbose_name': 'Evento predefinido',
                'verbose_name_plural': 'Eventos predefinidos',
            },
        ),
    ]
