# Generated by Django 4.0.3 on 2022-05-17 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de publico',
                'verbose_name_plural': 'Tipo de publico',
            },
        ),
        migrations.AddField(
            model_name='eventtipe',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='default_event.group', verbose_name='Tipo de publico'),
            preserve_default=False,
        ),
    ]
