# Generated by Django 4.0.3 on 2022-05-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='items',
            new_name='ages',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='adress',
            new_name='address',
        ),
    ]
