# Generated by Django 4.0.3 on 2022-05-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site',
            new_name='items',
        ),
    ]
