# Generated by Django 4.0.3 on 2022-05-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_event', '0002_group_eventtipe_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtipe',
            name='banquetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_event.banquetry', verbose_name='Banqueteria'),
        ),
        migrations.AlterField(
            model_name='eventtipe',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default_event.group', verbose_name='Tipo de publico'),
        ),
        migrations.AlterField(
            model_name='eventtipe',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_event.music', verbose_name='Musica'),
        ),
        migrations.AlterField(
            model_name='eventtipe',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_event.site', verbose_name='Recinto'),
        ),
        migrations.AlterField(
            model_name='eventtipe',
            name='toys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default_event.toys', verbose_name='Juegos'),
        ),
        migrations.AlterField(
            model_name='group',
            name='items',
            field=models.CharField(default=None, max_length=100, verbose_name='Tipo de publico'),
            preserve_default=False,
        ),
    ]
