# Generated by Django 4.0.3 on 2022-05-17 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_event', '0004_alter_toys_options_alter_eventtipe_toys_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toys',
            new_name='Entertainment',
        ),
        migrations.RenameField(
            model_name='eventtipe',
            old_name='toys',
            new_name='entertainment',
        ),
        migrations.AlterField(
            model_name='eventtipe',
            name='banquetry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default_event.banquetry', verbose_name='Banqueteria'),
        ),
    ]
